version: '3'

services:
  app:
    build: 
      context: ./app
    networks:
      - nodenetwork
    tty: true
    image: gsoldateli/node-app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node server.js
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=nodedb
    networks:
      - nodenetwork
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: gsoldateli/nginx:prod
    container_name: nginx
    networks:
      - nodenetwork
    ports:
      - "8080:80"
networks:
  nodenetwork:
    driver: bridge